---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      package:
        update_cache: yes

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php
      package:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest

- hosts: db_servers
  become: true
  tasks:
 
    - name: install mariadb
      package:
        name: mariadb-server 
        state: latest

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      package:
        name: samba
        state: latest
